// frontend/src/views/Login.vue
<template>
  <a-layout class="login-layout">
    <a-layout-content class="login-content">
      <a-card title="Iniciar sesión" class="login-card">
        <LoginForm :form="form" @submit="handleLogin" />
      </a-card>
    </a-layout-content>
  </a-layout>
</template>

<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { message } from 'ant-design-vue';
import { login } from '@/api/auth'; // Ajusta la ruta según tu estructura
import LoginForm from '@/components/auth/LoginForm.vue';

const form = ref({
  email: '',
  password: '',
  userType: ''
});

const router = useRouter();

const handleLogin = async () => {
  try {
    const { token } = await login(form.value);
    localStorage.setItem('token', token);
    message.success('Inicio de sesión exitoso');
    router.push('/');
  } catch (error) {
    message.error(error.response?.data?.message || 'Error al iniciar sesión');
  }
};
</script>

<style scoped>
@import '@/assets/auth/login.css';
</style>

// mi-react-app/src/components/Login.js
// src/components/Login.js
import React, { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import './Login.css';  // Archivo de estilos opcional

function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handleLogin = async (e) => {
    e.preventDefault();
    setLoading(true);

    try {
      const response = await axios.post('http://localhost:3001/auth/login', {
        email,
        password,
      });

      if (response.data.token) {
        localStorage.setItem('token', response.data.token);
        navigate('/home');  // Redirige a la página de inicio
      } else {
        setError('Email o contraseña incorrectos');
      }
    } catch (err) {
      setError('Credenciales incorrectas o error en el servidor');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-container">
      <form onSubmit={handleLogin} className="login-form">
        <h2>Iniciar Sesión</h2>
        {error && <p className="error">{error}</p>}
        <div className="form-group">
          <label>Email</label>
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
          />
        </div>
        <div className="form-group">
          <label>Contraseña</label>
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
        </div>
        <button type="submit" disabled={loading}>
          {loading ? 'Cargando...' : 'Iniciar Sesión'}
        </button>
      </form>
    </div>
  );
}

export default Login;
